#Latent Topics Generated by LDA AND LSA 

# Topics generated by LDA 
# IN LDA Tecnique the optinul number of the topics which are generated are 
# Most common words in the LDA are abil	abov	across	all	analys	appendix	applic	attent	avail	base	better	bloomberg	both	chain
# The Optimul number of K in LDA is 60 

#Topics generated by LSA 
# IN LSA Tecnique the optinul number of the topics which are generated are 
#Most common words in LSA are abil	abov	across	all	analys	appendix	applic	attent	avail	base	better	bloomberg	both	chain	coattent	construct	context	correl	cosearch	coview	cross	data
# Which are having the same probablity as that of the LDA 

# Generated all the Values in Both the LSA Analysis and LDA analysis are quite same
# IN LDA the optinul number of K is 60 
# where as in LSA the optinul number of the words which aee heavily used aer 30 
# as the probablities are mentioned in the Q1a_term_Ratnam2

